In [1]:
#import libraries
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [8]:
s = pd.read_csv('statewire_2017.csv')

In [13]:
c = s.loc[s['State'] == 'CALIFORNIA']

In [14]:
c.head()

,State,Jurisdiction,A.O. Number,Judge,Prosecutor,Offense,Type,Location,Application Date,Original Order (Days),...,Total Cost($),Other Than Manpower Cost ($),Arrests,Trials,Motions Granted,Motions Denied,Motions Pending,Persons Convicted,Cost Related,Results Related
46,CALIFORNIA,ALAMEDA,2017-1,ROLEFSON,O'MALLEY,MURDER,WC,D,02/24/2017,30.0,...,"28,651","1,583",0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
47,CALIFORNIA,ALAMEDA,2017-2,ROLEFSON,O'MALLEY,MURDER,WC,D,01/27/2017,30.0,...,"73,922","17,381",0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
48,CALIFORNIA,ALAMEDA,2017-3,ROLEFSON,O'MALLEY,MURDER,WC,D,02/14/2017,30.0,...,"26,660","3,175",0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
49,CALIFORNIA,ALAMEDA,2017-4,ROLEFSON,O'MALLEY,OTHER,WC,D,05/11/2017,30.0,...,"231,648","13,692",0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
50,CALIFORNIA,ALAMEDA,2017-5,ROLEFSON,O'MALLEY,OTHER,"WC,EE",O,05/11/2017,30.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,RELATED TO NO. 2017-4,NaN

In [12]:
c.Jurisdiction.unique()

array(['ALAMEDA', 'BUTTE', 'CONTRA COSTA', 'Fourth Appellate District',
       'FRESNO', 'IMPERIAL', 'KERN', 'LOS ANGELES', 'MERCED', 'ORANGE',
       'RIVERSIDE', 'SACRAMENTO', 'SAN BERNARDINO', 'SAN DIEGO',
       'SAN JOAQUIN', 'SAN LUIS OBISPO', 'SANTA CLARA', 'SANTA CRUZ',
       'SOLANO', 'STANISLAUS', 'TULARE', 'VENTURA', 'YOLO'], dtype=object)

In [ ]:
c.